### ISSUE TITLE
Don't require yarn to install / only using npm

### ISSUE THREAD

**Issue by masbaehr** [rfoel/react-font-loader#80]
Hi, im using only npm and not yarn, and was not able to install. Is there a way to build with npm only?

**Comment by rfoel** [comment]
It does not matter what you're using, it's a package, you can install using either npm or yarn. Can you paste the error?

**Comment by masbaehr** [comment]
Hi, the error is: 

'yarn' is not recognized as an internal or external command,
operable program or batch file.

Maybe because of "    "postinstall": "yarn build" in package.json ?

**Comment by rfoel** [comment]
True, I forgot it was there. I will remove and publish a new release.

**Comment by rfoel** [comment]
@masbaehr published under v2
